#!/usr/bin/env node
/**
 * Local stand-in for the Supabase edge + a scripted LLM provider, for the hard-512MB acceptance run.
 *
 *   node scripts/f2llm/acceptance/gateway.mjs            (env: PORT=54321, POSTGREST=http://127.0.0.1:3001, JWT_SECRET=...)
 *
 *   /auth/v1/user          verifies an HS256 access token and returns the user (what GoTrue does for getUser/getClaims)
 *   /rest/v1/*             proxied to a REAL PostgREST in front of the real Postgres (RLS + security-definer functions apply)
 *   /storage/v1/object/*   in-memory object store (upload / download / remove) — enough for the upload + extraction routes
 *   /llm/v1/chat/completions   scripted OpenAI-compatible provider (SSE); answers from the [[n]] sources it is given
 *
 * Test infrastructure only. It holds no real secrets: the JWT secret is a throwaway generated by the driver.
 */
import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import { createServer } from "node:http";

const PORT = Number(process.env.PORT ?? 54321);
const POSTGREST = process.env.POSTGREST ?? "http://127.0.0.1:3001";
const SECRET = process.env.JWT_SECRET ?? "";
if (SECRET.length < 32) {
  console.error("JWT_SECRET (>= 32 chars) is required");
  process.exit(2);
}
const LLM_DELAY_MS = Number(process.env.LLM_DELAY_MS ?? 25);

const b64u = (b) => Buffer.from(b).toString("base64url");
function verify(token) {
  const [h, p, s] = String(token ?? "").split(".");
  if (!h || !p || !s) return null;
  const exp = createHmac("sha256", SECRET).update(`${h}.${p}`).digest();
  const got = Buffer.from(s, "base64url");
  if (got.length !== exp.length || !timingSafeEqual(got, exp)) return null;
  const claims = JSON.parse(Buffer.from(p, "base64url").toString("utf8"));
  if (claims.exp && claims.exp < Date.now() / 1000) return null;
  return claims;
}

const objects = new Map(); // "bucket/path" -> { buf, type }
const stats = { auth: 0, rest: 0, storage: 0, llm: 0, llmActive: 0, llmMaxActive: 0, rpc: {} };

async function body(req) {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  return Buffer.concat(chunks);
}
const send = (res, status, data, headers = {}) => {
  const buf = Buffer.isBuffer(data) ? data : Buffer.from(typeof data === "string" ? data : JSON.stringify(data));
  res.writeHead(status, { "content-type": typeof data === "string" || Buffer.isBuffer(data) ? (headers["content-type"] ?? "application/octet-stream") : "application/json", "content-length": buf.length, ...headers });
  res.end(buf);
};

// ---------------------------------------------------------------------------------------------- LLM
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
function answerFor(messages) {
  const text = messages.map((m) => (typeof m.content === "string" ? m.content : JSON.stringify(m.content))).join("\n");
  const last = [...messages].reverse().find((m) => m.role === "user");
  const q = typeof last?.content === "string" ? last.content : "";
  const arabic = /[؀-ۿ]/.test(q);
  // a compliant model cites [[1]] when the prompt carries numbered sources, and refuses otherwise
  const hasSources = /index="1"/.test(text);
  if (hasSources) return arabic ? "بحسب الملفات المرفقة، وجدت المعلومة المطلوبة. [[1]]" : "According to the attached files, I found the requested information. [[1]]";
  return arabic ? "لم أجد هذه المعلومة في الملفات المرفقة." : "I could not find this information in the attached files.";
}
async function llm(req, res) {
  const raw = JSON.parse((await body(req)).toString("utf8") || "{}");
  stats.llm++;
  stats.llmActive++;
  stats.llmMaxActive = Math.max(stats.llmMaxActive, stats.llmActive);
  try {
    const answer = answerFor(raw.messages ?? []);
    if (raw.stream) {
      res.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache" });
      res.write(`data: ${JSON.stringify({ id: "mock", model: raw.model ?? "mock", choices: [{ index: 0, delta: { role: "assistant", content: "" } }] })}\n\n`);
      const parts = answer.match(/.{1,12}/gu) ?? [answer];
      for (const p of parts) {
        await sleep(LLM_DELAY_MS);
        res.write(`data: ${JSON.stringify({ id: "mock", model: raw.model ?? "mock", choices: [{ index: 0, delta: { content: p } }] })}\n\n`);
      }
      res.write(`data: ${JSON.stringify({ id: "mock", model: raw.model ?? "mock", choices: [{ index: 0, delta: {}, finish_reason: "stop" }], usage: { prompt_tokens: 120, completion_tokens: 20 } })}\n\n`);
      res.write("data: [DONE]\n\n");
      res.end();
    } else {
      send(res, 200, { id: "mock", model: raw.model ?? "mock", choices: [{ index: 0, message: { role: "assistant", content: answer }, finish_reason: "stop" }], usage: { prompt_tokens: 120, completion_tokens: 20 } });
    }
  } finally {
    stats.llmActive--;
  }
}

// ---------------------------------------------------------------------------------------------- main
createServer(async (req, res) => {
  try {
    const url = new URL(req.url, "http://gw");
    const p = url.pathname;

    if (p === "/__stats") return send(res, 200, { ...stats, objects: objects.size });
    if (p === "/__ping") return send(res, 200, { ok: true });

    if (p === "/auth/v1/user") {
      stats.auth++;
      const claims = verify((req.headers.authorization ?? "").replace(/^Bearer\s+/i, ""));
      if (!claims?.sub || claims.role !== "authenticated") return send(res, 401, { code: 401, error_code: "bad_jwt", msg: "invalid JWT" });
      return send(res, 200, { id: claims.sub, aud: "authenticated", role: "authenticated", email: claims.email ?? `${claims.sub}@acceptance.test`, app_metadata: {}, user_metadata: {}, created_at: "2026-01-01T00:00:00Z" });
    }
    if (p.startsWith("/auth/v1/.well-known/jwks.json")) return send(res, 200, { keys: [] });

    if (p.startsWith("/rest/v1/")) {
      stats.rest++;
      const rpcName = /^\/rest\/v1\/rpc\/([a-z_0-9]+)/.exec(p)?.[1];
      if (rpcName) stats.rpc[rpcName] = (stats.rpc[rpcName] ?? 0) + 1;
      const target = POSTGREST + p.slice("/rest/v1".length) + url.search;
      const headers = {};
      for (const [k, v] of Object.entries(req.headers)) if (!["host", "connection", "content-length", "accept-encoding"].includes(k)) headers[k] = v;
      const method = req.method ?? "GET";
      const data = ["GET", "HEAD"].includes(method) ? undefined : await body(req);
      const upstream = await fetch(target, { method, headers, body: data, redirect: "manual" });
      const buf = Buffer.from(await upstream.arrayBuffer());
      const out = {};
      upstream.headers.forEach((v, k) => {
        if (!["transfer-encoding", "content-encoding", "connection", "content-length"].includes(k)) out[k] = v;
      });
      res.writeHead(upstream.status, { ...out, "content-length": buf.length });
      return res.end(method === "HEAD" ? undefined : buf);
    }

    if (p === "/storage/v1/bucket/files") return send(res, 200, { id: "files", name: "files", public: false });
    if (p.startsWith("/storage/v1/object")) {
      stats.storage++;
      const rest = decodeURIComponent(p.slice("/storage/v1/object".length)).replace(/^\/(authenticated|public|sign)\//, "/").replace(/^\//, "");
      if (req.method === "DELETE") {
        const { prefixes } = JSON.parse((await body(req)).toString("utf8") || "{}");
        const removed = [];
        for (const pre of prefixes ?? []) if (objects.delete(`${rest}/${pre}`)) removed.push({ name: pre });
        return send(res, 200, removed);
      }
      if (req.method === "POST" || req.method === "PUT") {
        const buf = await body(req);
        objects.set(rest, { buf, type: String(req.headers["content-type"] ?? "application/octet-stream") });
        return send(res, 200, { Key: rest, Id: randomUUID() });
      }
      if (req.method === "GET" || req.method === "HEAD") {
        const o = objects.get(rest);
        if (!o) return send(res, 404, { statusCode: "404", error: "not_found", message: "Object not found" });
        return send(res, 200, o.buf, { "content-type": o.type });
      }
    }

    if (p === "/llm/v1/chat/completions" && req.method === "POST") return await llm(req, res);

    send(res, 404, { error: "gateway: no route", path: p });
  } catch (e) {
    console.error("[gateway] error:", e?.message ?? e);
    if (!res.headersSent) send(res, 500, { error: "gateway error" });
    else res.end();
  }
}).listen(PORT, "0.0.0.0", () => console.log(`[gateway] listening on :${PORT} → postgrest ${POSTGREST}`));

void b64u;
